language: go
go:
- 1.13.x
services:
- docker
cache:
  directories:
  - $GOPATH/pkg/mod
  - $HOME/.cache/go-build
env:
  global:
  - GO111MODULE=on
script:
- make install-deps
- make lint
- make docker.build
deploy:
- provider: script
  skip_cleanup: true
  script: make docker.push
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux