---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: aws-auth-refresher
  name: aws-auth-refresher
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: aws-auth-refresher
  name: aws-auth-refresher
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: aws-auth-refresher
  name: aws-auth-refresher
  namespace: kube-system
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: aws-auth-refresher
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aws-auth-refresher
