---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
{{ include "aws-auth-refresher.labels" . | indent 4 }}
  name: {{ include "aws-auth-refresher.fullname" . }}
  namespace: kube-system
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: {{ template "aws-auth-refresher.fullname" . }}
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "aws-auth-refresher.fullname" . }}