---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
{{ include "aws-auth-refresher.labels" . | indent 4 }}
  name: {{ include "aws-auth-refresher.fullname" . }}
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - get
    - update